# Generated by Django 3.2.8 on 2021-10-28 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(999),
                    django.core.validators.MinValueValidator(1)
                ]
            ),
        ),
    ]
