version: '3'

services:
    redis:
        image: redis:5.0
        command: redis-server
    backend:
        build:
          context: .
          dockerfile: Dockerfile.backend
        volumes:
            - './backend:/src'
        environment:
            - HOST_ENV=dev
            - REDIS_HOST=redis
        depends_on:
            - redis
        ports:
            - 8080:8080
    frontend:
        build:
          context: .
          dockerfile: Dockerfile.frontend
          args:
            - API_HOST=http://localhost:8080
        environment:
            - HOST_ENV=dev
        ports:
            - 3000:3000