FROM node:16

WORKDIR /src

RUN npm install -g serve

# install dependencies
COPY ./frontend/package.json ./frontend/yarn.lock /src/
RUN yarn install --frozen-lockfile

# copy the frontend source code
COPY ./frontend/public /src/public
COPY ./frontend/src /src/src

# retrieve api host
ARG API_HOST
ENV REACT_APP_API_HOST ${API_HOST}

RUN yarn build

# expose the port 3000
EXPOSE 3000


CMD serve -l tcp://0.0.0.0:3000 build
